// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210520013250_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("api.Models.Cidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Populacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("api.Models.Fronteiras", b =>
                {
                    b.Property<int>("CidadesId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadesId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("CidadesId1", "CidadesId2");

                    b.HasIndex("CidadesId2");

                    b.ToTable("Fronteiras");
                });

            modelBuilder.Entity("api.Models.Fronteiras", b =>
                {
                    b.HasOne("api.Models.Cidades", "Cidade1")
                        .WithMany()
                        .HasForeignKey("CidadesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Cidades", "Cidade2")
                        .WithMany()
                        .HasForeignKey("CidadesId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade1");

                    b.Navigation("Cidade2");
                });
#pragma warning restore 612, 618
        }
    }
}
